# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6706616b1fa48668d71bdd732338dd1f1230ff3cbfbcfce0c9e6fecba96aac824ab91199352153eabe4ceec2406b610fbc40eedc76291b57804d3bed117f3c4c

test:
  secret_key_base: 256dee1d19eb46aa80a995ca2c693c7c0c0e6c2e14211d66d0d3e9da9f754a9440f7d9ebdb67c23d53f5320ee4ad97ca9c3d5bb3e7da52f02e1aa07270e45970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
